Updates Pinky-Promise to use Swift5 Result type.
willowtreeapps/PinkyPromise pull request #69
Opened 2019-08-16 15:06 UTC by samshiffman321

2019-08-16 15:25 UTC, kconner reviewed
We would also need to update the README and the example playground due to syntax changes.

2019-08-16 15:25 UTC, kconner commented on Sources/Promise.swift
> +    public typealias Observer = (Result<Value, Error>) -> Void
Should we make the error type of Promise generic to match Result?

2019-08-16 15:25 UTC, kconner commented on PinkyPromise.xcodeproj/project.pbxproj
> +				SWIFT_VERSION = 5.0;
Since we are changing the Swift version, we need to save the latest Swift 4 release with a swift-4 branch, as we've done for prior versions.

2019-08-16 15:25 UTC, kconner commented on Sources/Promise.swift
> +            }))
Was this a necessary change? Did the migrator do it?

2019-08-16 15:25 UTC, kconner commented on Sources/PromiseQueue.swift
> +    func enqueue(in queue: PromiseQueue<Value>) {
Shoot, did this ever work before? We must have hidden this method from consumers for ages.

2019-08-16 15:25 UTC, kconner commented on Sources/Result.swift
> +public func zip<A, B>(_ resultA: Result<A, Error>, _ resultB: Result<B, Error>) -> Result<(A, B), Error> {
I'm guessing you confirmed the standard library has nothing like these zip functions?

2019-08-16 15:25 UTC, kconner commented on Sources/Promise.swift
> +    public typealias Observer = (Result<Value, Error>) -> Void
I guess it would depend on our goals. Compatibility is one.

2019-08-16 15:25 UTC, kconner commented on Sources/Result.swift
> +    init(create: () throws -> Success) {
All these methods will become hidden from library consumers, is that right? Is that desirable?

2019-08-16 15:39 UTC, kconner commented on Sources/Promise.swift
> +    public typealias Observer = (Result<Value, Error>) -> Void
Eventually, I think the story arc of PinkyPromise should end in one of two routes:

1. We deprecate the library and recommend everyone use `Combine.Publishers.Future` over `PinkyPromise.Promise` as soon as they can get on iOS 13 minimum, or
2. We keep PinkyPromise alive as a simplistic alternative framework.

Both options are valid, but I think either way we don't need the error type to be generic in this library. In one case we don't need it to be perfectly compatible; in the other we want it to be simple.

2019-08-16 15:43 UTC, kconner commented
We should also regenerate and save the documentation.

2019-08-16 16:00 UTC, samshiffman321 commented on Sources/Promise.swift
> +            }))
this was necessary, it kept yelling at me with "ambiguous use of init" so I had to specify which init method to use.

2019-08-16 16:02 UTC, kconner commented on Sources/Promise.swift
> +            }))
Oh, that makes sense. There would have been one supplied by the standard library too.

So then, would [the one in the standard library](https://developer.apple.com/documentation/swift/result/3139399-init) suffice? Does it do the same thing?

2019-08-16 16:02 UTC, samshiffman321 commented on Sources/Result.swift
> +    init(create: () throws -> Success) {
ah hm... not sure if thats desirable, I was just trying to satisfy warnings that said declaring these methods `public` was redundant

2019-08-16 16:04 UTC, samshiffman321 commented
looks like CI failed because swift 5 isn't supported? is there anything we can do about that?

2019-08-16 16:04 UTC, kconner commented on Sources/Result.swift
> +public func zip<A, B>(_ resultA: Result<A, Error>, _ resultB: Result<B, Error>) -> Result<(A, B), Error> {
The diff would be easier to read if these had stayed put at the bottom of the file. Is there a reason to move them up?

2019-08-16 16:05 UTC, kconner commented on Sources/Result.swift
> +    init(create: () throws -> Success) {
Oh! I had it in my head that an undecorated member of a public type would be internal, not public … but maybe the rules changed, or maybe I had the wrong idea in the first place.

2019-08-16 16:06 UTC, kconner commented
Re: CI failing, I think it means we need to update `.circleci/config.yml` and request a more current build environment.

2019-08-16 16:07 UTC, kconner commented on Sources/PromiseQueue.swift
> +    func enqueue(in queue: PromiseQueue<Value>) {
Disregard, I read this diff backwards.

2019-08-16 16:11 UTC, kconner commented on PinkyPromise.xcodeproj/project.pbxproj
> +				SWIFT_VERSION = 5.0;
Oh hey, we already have that! It's a version behind, though. We should update that to match the latest release's tag.
We also need to merge the last release to master, then fast forward develop to master, before merging this. @andrewroycarter

2019-08-16 16:12 UTC, samshiffman321 commented on Sources/Result.swift
> +public func zip<A, B>(_ resultA: Result<A, Error>, _ resultB: Result<B, Error>) -> Result<(A, B), Error> {
I had just taken the helper methods out of the `Result` type and removed the unused result type. I did not intentionally re-order these methods, I could try to put them in the same order as before if necessary.

2019-08-16 16:14 UTC, samshiffman321 commented on Sources/Promise.swift
> +            }))
good question, I will try that and see if we can consolidate

2019-08-16 16:14 UTC, kconner commented on Sources/Result.swift
> +    func value() throws -> Success {
`get()` is provided by the standard library. I think we should recommend consumers just use that, and remove this method.

2019-08-16 16:15 UTC, kconner commented on Sources/Result.swift
> +    init(create: () throws -> Success) {
`init(catching:)` is provided by the standard library. I think we should recommend consumers just use that, and remove this initializer.

2019-08-16 16:16 UTC, kconner commented on Sources/Result.swift
> +public func zip<A, B>(_ resultA: Result<A, Error>, _ resultB: Result<B, Error>) -> Result<(A, B), Error> {
Having reread this file, yeah, in my opinion we want the extension at the top where the enum used to be, and then the zip functions.

2019-08-16 17:52 UTC, samshiffman321 commented on Sources/Result.swift
> +    func value() throws -> Success {
done

2019-08-16 17:52 UTC, samshiffman321 commented on Sources/Result.swift
> +    init(create: () throws -> Success) {
we are now using `init(catching:)`, and removed init(create:)

2019-08-16 17:53 UTC, samshiffman321 commented on Sources/Result.swift
> +public func zip<A, B>(_ resultA: Result<A, Error>, _ resultB: Result<B, Error>) -> Result<(A, B), Error> {
reordered this file to put the extension at the top.

2019-08-16 17:53 UTC, samshiffman321 commented on Sources/Promise.swift
> +            }))
removed `init(create:)` in favor of the provided `init(catching:)`

2019-08-20 15:48 UTC, kconner commented on PinkyPromise.xcodeproj/project.pbxproj
> +				SWIFT_VERSION = 5.0;
(did this)

2019-08-20 15:49 UTC, kconner commented on Sources/Promise.swift
> +    public typealias Observer = (Result<Value, Error>) -> Void
We decided to not make the error type generic in Promise, and therefore Promise will depend on the error type being Error in Swift.Result.

2019-08-20 16:04 UTC, andrewroycarter commented on Sources/Promise.swift
> +    public typealias Observer = (Result<Value, Error>) -> Void
After spending some time looking more at https://developer.apple.com/documentation/combine/future/promise I think it makes the most sense to expect that people move to the apple frameworks once they can target iOS 13, and let Pinky Promise continue being a simple solution for app supporting older targets. PinkyPromise and Apple's Promise are _so_ similar I don't think there's a need to provide a simpler alternative.

2019-08-21 13:44 UTC, kconner requested changes
Just to note where we left off, we need to:

- Review and update the README, the example playground, and all code documentation comments. Result is now external (previously we said this library consists mainly of two types; now it consists mainly of one and borrows one), and there may be usage syntax changes related to that. We also had a type comment for Result where we should perhaps defer to Apple's docs at this point.
- Regenerate and save the documentation (instructions are in CONTRIBUTING.md)

2019-09-10 15:21 UTC, andrewroycarter approved these changes

2019-09-10 17:19 UTC, merged